CREATE TABLE usuarios (
    id INT PRIMARY KEY AUTO_INCREMENT,
    public_id INT NOT NULL UNIQUE,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    permissao ENUM('ADMINISTRADOR', 'USUARIO', 'MODERADOR', 'SUPORTE', 'PROPRIETARIO', 'DESENVOLVEDOR', 'BANIDO') NOT NULL DEFAULT 'USUARIO',
    status BOOLEAN NOT NULL DEFAULT TRUE,
    data_cadastro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);